# Generated by Django 4.2.17 on 2024-12-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_hospitals', to='api.client'),
        ),
        migrations.AddField(
            model_name='medics',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_medics', to='api.client'),
        ),
    ]
