# Generated by Django 4.2.17 on 2024-12-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_sessions_date_remove_sessions_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='appointment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
