# Generated by Django 4.2.17 on 2024-12-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_sessions_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='medics',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
